### ISSUE TITLE
Rejuvenation enchantment spitting out warning on console 

### ISSUE THREAD

**Issue by DannyTheKO** [Athlaeos/EnchantsSquaredRewritten#19]
Hi,
First off your plugin work great on 1.20.6, except the Rejuvenation enchantment is spitting out warning on console, but the enchant itself seem to work

Here is the console respone, hope it help
```
[04:04:34 WARN]: [EnchantsSquared] Task #35 for EnchantsSquared v2.5.10 generated an exception
java.lang.IllegalArgumentException: Damage cannot be negative
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1547) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.utility.ItemUtils.damageItem(ItemUtils.java:94) ~[EnchantsSquared.jar:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.utility.ItemUtils.damageItem(ItemUtils.java:138) ~[EnchantsSquared.jar:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.enchantments.regular_interval.Rejuvenation.execute(Rejuvenation.java:179) ~[EnchantsSquared.jar:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.managers.RegularIntervalEnchantmentClockManager.lambda$startClock$1(RegularIntervalEnchantmentClockManager.java:47) ~[EnchantsSquared.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.managers.RegularIntervalEnchantmentClockManager.lambda$startClock$2(RegularIntervalEnchantmentClockManager.java:47) ~[EnchantsSquared.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Athlaeos** [comment]
I haven't updated the plugin to 1.20.6 yet, there are a bunch more errors aside of this one. This error is caused by an api change. Thank you for reporting, though
