### ISSUE TITLE
Enchant squared issue

### ISSUE THREAD

**Issue by Dodo04-dal** [Athlaeos/EnchantsSquaredRewritten#21]
[00:58:06 WARN]: [EnchantsSquared] Task #7 for EnchantsSquared v2.5.10 generated an exception
java.lang.IllegalArgumentException: Damage cannot be negative
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1632) ~[paper-1.21.jar:1.21-37-dd49fba]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.utility.ItemUtils.damageItem(ItemUtils.java:98) ~[EnchantsSquared.jar:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.utility.ItemUtils.damageItem(ItemUtils.java:142) ~[EnchantsSquared.jar:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.enchantments.regular_interval.Rejuvenation.execute(Rejuvenation.java:179) ~[EnchantsSquared.jar:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.managers.RegularIntervalEnchantmentClockManager.lambda$startClock$1(RegularIntervalEnchantmentClockManager.java:47) ~[EnchantsSquared.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at EnchantsSquared.jar/me.athlaeos.enchantssquared.managers.RegularIntervalEnchantmentClockManager.lambda$startClock$2(RegularIntervalEnchantmentClockManager.java:47) ~[EnchantsSquared.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Ive been having this issue ever since 1.20.2 but as i go up in versions its becoming more and more frequent

**Comment by Athlaeos** [comment]
Known issue with 1.21, will be fixed soon. Also, the recent ES update aiming for 1.21 compatibility failed and I don't recommend using it yet
