### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to EnchantsSquared v2.5

### ISSUE THREAD

**Issue by Darmoed228** [Athlaeos/EnchantsSquaredRewritten#4]
Hello.
I get an error like this in the console. Can this be fixed?

`[02:45:35 ERROR]: Could not pass event EntityDamageByEntityEvent to EnchantsSquared v2.5
java.lang.IllegalArgumentException: data (class java.lang.Double) should be class java.lang.Void
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2114) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2109) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2098) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2078) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2058) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2053) ~[paper-1.20.1.jar:git-Paper-43]
        at me.athlaeos.enchantssquared.animations.Flash.play(Flash.java:26) ~[EnchantsSquared.jar:?]
        at me.athlaeos.enchantssquared.enchantments.on_attack.Nausea.onAttack(Nausea.java:76) ~[EnchantsSquared.jar:?]
        at me.athlaeos.enchantssquared.listeners.EntityDamageListener.onEntityDamagedByEntity(EntityDamageListener.java:69) ~[EnchantsSquared.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor190.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-43]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:253) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1181) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1036) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:980) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1215) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2194) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1432) ~[?:?]
        at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:406) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1348) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2875) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2799) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]`

**Comment by kju196** [comment]
I also have this problem.
   ```
 [07:31:02 ERROR]: Could not pass event EntityDamageByEntityEvent to EnchantsSquared v2.5                                                                                                    java.lang.IllegalArgumentException: data (class java.lang.Double) should be class java.lang.Void                                                                                                    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.1-jre.jar:?]                                                                                       at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2114) ~[paper-1.20.1.jar:git-Paper-49]                                                                          at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2109) ~[paper-1.20.1.jar:git-Paper-49]                                                                          at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2098) ~[paper-1.20.1.jar:git-Paper-49]                                                                          at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2078) ~[paper-1.20.1.jar:git-Paper-49]                                                                          at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2058) ~[paper-1.20.1.jar:git-Paper-49]                                                                          at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.spawnParticle(CraftWorld.java:2053) ~[paper-1.20.1.jar:git-Paper-49]                                                                          at me.athlaeos.enchantssquared.animations.Flash.play(Flash.java:26) ~[EnchantsSquared.jar:?]                                                                                                at me.athlaeos.enchantssquared.enchantments.on_attack.Nausea.onAttack(Nausea.java:76) ~[EnchantsSquared.jar:?]                                                                              at me.athlaeos.enchantssquared.listeners.EntityDamageListener.onEntityDamagedByEntity(EntityDamageListener.java:69) ~[EnchantsSquared.jar:?]                                                at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]                                                                             at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-49]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-49]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:253) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1181) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1036) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:980) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1215) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2194) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1432) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1348) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2875) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
```

**Comment by Athlaeos** [comment]
I am aware of this issue, it's a problem introduced with the 1.20 update which apparently changed the way a specific particle is played out. You can remove the errors for the time being by setting "flash" type animations to "none" in config.yml
